### ISSUE TITLE
Maybe FlutterSentry.wrap() can await for the async inner function?

### ISSUE THREAD

**Issue by fzyzcjy** [futureware-tech/flutter_sentry#37]
**Describe the bug**

Thanks for the library!

When reading the source code, I find `FlutterSentry.wrap()` doing things like -

```
T wrap(T Function() f){
    return runZoned<T>(() {
        ...
        return f();
    });
}
```

However, IMHO, in most of the cases, ***the f is async function***. Thus I propose to do -

```
Future<T> wrap(Future<T> Function() f) async {
    return await runZoned<T>(() {
        ...
        return await f();
    });
}
```

(notice the `await` and the `Future`s)

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Web (If applicable):**
N/A

**Smartphone (If applicable):**
N/A

**Additional context**
N/A

**Comment by dotdoom** [comment]
@fzyzcjy thanks for the report!  Have you perhaps closed it by accident?

There was "await" in some previous version of the `.wrap()` API, but it was deemed unnecessary because the Zone where Future is executed is preserved, even if we don't await.  The Dart documentation *at that time at least* said that awaiting non-Futures is a bad idea, so we removed await to keep the interface generic and accept any type.  You can still *await* the `.wrap` method though!

Does this answer the question, or have you encountered an edge case where await inside would be necessary?  I think we can try to workaround this and keep generic type with [`FutureOr`](https://api.dart.dev/stable/2.9.0/dart-async/FutureOr-class.html).

**Comment by fzyzcjy** [comment]
Yes I have soon found that zone is happy without await, thus I close without accident. Thanks very much for your reply!
